### ISSUE TITLE
YAML/TOML frontmatter

### ISSUE THREAD

**Issue by heitorPB** [jethrokuan/cortex#5]
Awesome theme!

Could you provide an example of a complete markdown entry, with the frontmatter? What are the things supported? title, date, author, backlinks, tags, categories?

**Comment by jethrokuan** [comment]
Front matter is the same as what Hugo supports, nothing additional.

Backlinks are computed by the theme, not something you explicitly specify. E.g. if you have a file with `{{<relref "operating_systems.md" >}}`, then in "operating systems" you'll see a backlink to this file.
